# Generated by Django 5.1.3 on 2024-12-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulado',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='consulado',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True, verbose_name='Longitud'),
        ),
    ]
