# Generated by Django 5.1.3 on 2024-12-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_consulado_latitud_alter_consulado_longitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embajada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Embajada')),
                ('pais', models.CharField(max_length=100, verbose_name='Pais del Embajada')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Nombre de la Ciudad')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Direccion')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de telefono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electronico')),
                ('latitud', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True, verbose_name='Longitud')),
            ],
            options={
                'verbose_name': 'Embajada',
                'verbose_name_plural': 'Embajadas',
                'ordering': ['pais', 'ciudad'],
            },
        ),
    ]
