# Generated by Django 5.1.3 on 2024-12-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_embajada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulado',
            name='latitud',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='consulado',
            name='longitud',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='embajada',
            name='latitud',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='embajada',
            name='longitud',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitud'),
        ),
    ]
