# Generated by Django 5.1.3 on 2024-12-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_consulado_latitud_alter_consulado_longitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulado',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='descripcion'),
        ),
        migrations.AddField(
            model_name='consulado',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='titulo'),
        ),
        migrations.AddField(
            model_name='embajada',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='descripcion'),
        ),
        migrations.AddField(
            model_name='embajada',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='titulo'),
        ),
    ]
