# Generated by Django 5.1.3 on 2024-12-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_consulado_descripcion_consulado_titulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del comercio')),
                ('pais', models.CharField(max_length=100, verbose_name='Pais del comercio')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Nombre de la Ciudad')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Direccion')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de telefono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electronico')),
                ('latitud', models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitud')),
                ('longitud', models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitud')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='titulo')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='descripcion')),
            ],
            options={
                'verbose_name': 'Comercio',
                'verbose_name_plural': 'Comercios',
                'ordering': ['pais', 'ciudad'],
            },
        ),
    ]
