# Generated by Django 5.1.3 on 2024-12-06 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_comercio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del restaurante')),
                ('pais', models.CharField(max_length=100, verbose_name='Pais del restaurante')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Nombre de la Ciudad')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Direccion')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de telefono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electronico')),
                ('latitud', models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitud')),
                ('longitud', models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitud')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='titulo')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='descripcion')),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
                'ordering': ['pais', 'ciudad'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
