# Generated by Django 5.1.3 on 2024-12-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_restaurante_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
