# Generated by Django 5.1.3 on 2024-12-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_abogado_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='descripcion',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
