# Generated by Django 5.1.3 on 2024-12-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_abogado_descripcion_alter_abogado_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
