# Generated by Django 5.1.3 on 2024-12-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_abogado_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='abogado',
            name='precio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='precio'),
        ),
    ]
