# Generated by Django 5.1.3 on 2024-12-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/abogados'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/blog'),
        ),
    ]
