# Generated by Django 5.1.3 on 2024-12-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_abogado_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='abogado',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='titulo'),
        ),
    ]
