# Generated by Django 5.1.3 on 2024-12-08 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_abogado_asesoriajuridicageneral_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abogado',
            old_name='redaccionyrevisiondedocuemntos',
            new_name='redaccionyrevisiondedocumentos',
        ),
    ]
