# Generated by Django 5.1.3 on 2024-12-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_redaccionyrevisiondedocuemntos_abogado_redaccionyrevisiondedocumentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='abogado',
            name='asesoramientoparaemprendedores',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abogado',
            name='asesoramientoparatrabajadoresmigrantes',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abogado',
            name='asesoriaencasosdediborcioyseparacion',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abogado',
            name='asesoriaencasosdeviolenciaoabusos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abogado',
            name='asesoriaenherenciasytestamentos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abogado',
            name='asesoriaenreagrupacionfamiliar',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abogado',
            name='asesoriaparaexportaciondeproductos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abogado',
            name='asistenciaencasosdedespidos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abogado',
            name='capacitacionesytalleresjuridicos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abogado',
            name='defenzaencasosdedeportacion',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abogado',
            name='defenzaencasospenales',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abogado',
            name='propiedadintelectual',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abogado',
            name='prosesosdenaturalizacion',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abogado',
            name='traduccionylegalizaciondedocumentos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abogado',
            name='tramitesdepartidadenacimientoydefunciones',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abogado',
            name='tramitesdevisasypermisosdetrabajo',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
