# Generated by Django 5.1.3 on 2024-12-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_abogado_asesoramientoparaemprendedores_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abogado',
            old_name='asesoriaencasosdediborcioyseparacion',
            new_name='asesoriaencasosdedivorcioyseparacion',
        ),
        migrations.RenameField(
            model_name='abogado',
            old_name='defenzaencasosdedeportacion',
            new_name='defensaencasosdedeportacion',
        ),
        migrations.RenameField(
            model_name='abogado',
            old_name='prosesosdenaturalizacion',
            new_name='procesosdenaturalizacion',
        ),
    ]
