# Generated by Django 5.1.3 on 2024-12-08 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_rename_asesoriaencasosdediborcioyseparacion_abogado_asesoriaencasosdedivorcioyseparacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abogado',
            name='asesoramientoparatrabajadoresmigrantes',
        ),
        migrations.AddField(
            model_name='abogado',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
