# Generated by Django 5.1.3 on 2024-12-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_abogado_asesoramientoparatrabajadoresmigrantes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abogado',
            name='verificado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
