# Generated by Django 5.1.3 on 2024-12-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_comercio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='abogado',
            name='negocioacionyredacciondecontratos',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
