# Generated by Django 5.1.3 on 2024-12-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_abogado_negocioacionyredacciondecontratos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abogado',
            name='user',
        ),
        migrations.AlterField(
            model_name='abogado',
            name='asesoramientoparaemprendedores',
            field=models.BooleanField(blank=True, null=True, verbose_name='Asesoramiento para Emprendedores'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='asesoriaencasosdedivorcioyseparacion',
            field=models.BooleanField(blank=True, null=True, verbose_name='Asesoría en Casos de Divorcio y Separación'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='asesoriaencasosdeviolenciaoabusos',
            field=models.BooleanField(blank=True, null=True, verbose_name='Asesoría en Casos de Violencia o Abusos'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='asesoriaenherenciasytestamentos',
            field=models.BooleanField(blank=True, null=True, verbose_name='Asesoría en Herencias y Testamentos'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='asesoriaenreagrupacionfamiliar',
            field=models.BooleanField(blank=True, null=True, verbose_name='Asesoría en Reagrupación Familiar'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='asesoriajuridicageneral',
            field=models.BooleanField(blank=True, null=True, verbose_name='Asesoría Jurídica General'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='asesoriaparaexportaciondeproductos',
            field=models.BooleanField(blank=True, null=True, verbose_name='Asesoría para Exportación de Productos'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='asistenciaencasosdedespidos',
            field=models.BooleanField(blank=True, null=True, verbose_name='Asistencia en Casos de Despidos'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='capacitacionesytalleresjuridicos',
            field=models.BooleanField(blank=True, null=True, verbose_name='Capacitaciones y Talleres Jurídicos'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='ciudad',
            field=models.CharField(max_length=100, verbose_name='Nombre de la ciudad'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='defensaencasosdedeportacion',
            field=models.BooleanField(blank=True, null=True, verbose_name='Defensa en Casos de Deportación'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='defenzaencasospenales',
            field=models.BooleanField(blank=True, null=True, verbose_name='Defensa en Casos Penales'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='mediacionyarbitraje',
            field=models.BooleanField(blank=True, null=True, verbose_name='Mediación y Arbitraje'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='negocioacionyredacciondecontratos',
            field=models.BooleanField(blank=True, null=True, verbose_name='Negociación y Redacción de Contratos'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='pais',
            field=models.CharField(max_length=100, verbose_name='País del abogado'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='precio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='procesosdenaturalizacion',
            field=models.BooleanField(blank=True, null=True, verbose_name='Procesos de Naturalización'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='propiedadintelectual',
            field=models.BooleanField(blank=True, null=True, verbose_name='Propiedad Intelectual'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='redaccionyrevisiondedocumentos',
            field=models.BooleanField(blank=True, null=True, verbose_name='Redacción y Revisión de Documentos'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='representacionlegal',
            field=models.BooleanField(blank=True, null=True, verbose_name='Representación Legal'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='resumen',
            field=models.TextField(blank=True, null=True, verbose_name='Resumen'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='telefono',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de teléfono'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='traduccionylegalizaciondedocumentos',
            field=models.BooleanField(blank=True, null=True, verbose_name='Traducción y Legalización de Documentos'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='tramitesdepartidadenacimientoydefunciones',
            field=models.BooleanField(blank=True, null=True, verbose_name='Trámites de Partida de Nacimiento y Defunciones'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='tramitesdevisasypermisosdetrabajo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Trámites de Visas y Permisos de Trabajo'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='verificado',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Está verificado?'),
        ),
    ]
