# Generated by Django 5.1.3 on 2024-12-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_abogado_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/restaurante'),
        ),
    ]
