# Generated by Django 5.1.3 on 2024-12-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_restaurante_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subtitulo'),
        ),
    ]
