# Generated by Django 5.1.3 on 2024-12-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_restaurante_subtitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='images/comercio'),
        ),
    ]
