# Generated by Django 5.1.3 on 2024-12-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_restaurante_imagen_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='images/restaurante'),
        ),
    ]
