# Generated by Django 5.1.3 on 2024-12-14 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_tipoempresa_empresas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empresas',
            new_name='Empresa',
        ),
    ]
