# Generated by Django 5.1.3 on 2024-12-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comentario',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
