# Generated by Django 5.1.3 on 2024-12-18 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_perfil_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comercio',
            name='user',
        ),
        migrations.DeleteModel(
            name='Restaurante',
        ),
        migrations.DeleteModel(
            name='Comercio',
        ),
    ]
