# Generated by Django 5.1.3 on 2024-12-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_remove_comercio_user_delete_restaurante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='titulo',
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_header',
            field=models.ImageField(blank=True, null=True, upload_to='images/empresa/portada'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='parrafo1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo1'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='parrafo2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo2'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='parrafo3',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo3'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='parrafo4',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo4'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='parrafo5',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo5'),
        ),
    ]
