# Generated by Django 5.1.3 on 2024-12-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_remove_empresa_titulo_empresa_imagen_header_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/principal'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='imagen_header',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/header'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/portada'),
        ),
    ]
