# Generated by Django 5.1.3 on 2024-12-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_empresa_video_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='imagen_nosotros',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/nosotros'),
        ),
    ]
