# Generated by Django 5.1.3 on 2024-12-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_empresa_video_nosotros'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='imagen_nosotros_fondo',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/nosotros'),
        ),
    ]
