# Generated by Django 5.1.3 on 2024-12-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_empresa_imagen_nosotros_fondo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='imagen_gallerry1',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/galeria'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_gallerry2',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/galeria'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_gallerry3',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/galeria'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_gallerry4',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/galeria'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_gallerry5',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/galeria'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_gallerry6',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/galeria'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_gallerry7',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/galeria'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_gallerry8',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/galeria'),
        ),
    ]
