# Generated by Django 5.1.3 on 2024-12-22 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_empresa_imagen_gallerry1_empresa_imagen_gallerry2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='imagen_gallerry1',
            new_name='imagen_galeria1',
        ),
    ]
