# Generated by Django 5.1.3 on 2024-12-22 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_rename_imagen_gallerry1_empresa_imagen_galeria1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='imagen_gallerry2',
            new_name='imagen_galeria2',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='imagen_gallerry6',
            new_name='imagen_galeria3',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='imagen_gallerry3',
            new_name='imagen_galeria4',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='imagen_gallerry4',
            new_name='imagen_galeria5',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='imagen_gallerry5',
            new_name='imagen_galeria6',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='imagen_gallerry7',
            new_name='imagen_galeria7',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='imagen_gallerry8',
            new_name='imagen_galeria8',
        ),
    ]
