# Generated by Django 5.1.3 on 2024-12-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_empresa_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='menu_regalo1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='menu_regalo1'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='menu_regalo2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='menu_regalo2'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='menu_regalo3',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='menu_regalo3'),
        ),
    ]
