# Generated by Django 5.1.3 on 2024-12-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_empresa_menu_oferta1_empresa_menu_oferta2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='quienes_somos_activo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agregar sección'),
        ),
    ]
