# Generated by Django 5.1.3 on 2024-12-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_empresa_quienes_somos_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='quienes_somos_activo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agregar sección Sobre Nosotros'),
        ),
    ]
