# Generated by Django 5.1.3 on 2024-12-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_alter_empresa_quienes_somos_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='galeria_activo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agregar sección para vender menu de regalo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='menu_regalo_activo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agregar sección para vender menu de regalo'),
        ),
    ]
