# Generated by Django 5.1.3 on 2024-12-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_empresa_galeria_activo_empresa_menu_regalo_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='clientes_activo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agregar sección para ver clientes'),
        ),
    ]
