# Generated by Django 5.1.3 on 2024-12-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_empresa_clientes_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='galeria_activo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agregar sección Galería'),
        ),
    ]
