# Generated by Django 5.1.3 on 2024-12-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_alter_empresa_galeria_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='comentarios_activo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agregar sección de comentarios'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='contactar_activo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agregar sección para contactar'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='platos_menu_activo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agregar sección de platos'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='reservar_activo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agregar sección para reservas'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='galeria_activo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agregar sección de enventos'),
        ),
    ]
