# Generated by Django 5.1.3 on 2024-12-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_empresa_comentarios_activo_empresa_contactar_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='chefs_activo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agregar sección de chefs'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='eventos_activo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agregar sección de enventos'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='galeria_activo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agregar sección Galería'),
        ),
    ]
