# Generated by Django 5.1.3 on 2024-12-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_empresa_chefs_activo_empresa_eventos_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='menu_regalo1',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='menu_regalo2',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='menu_regalo3',
        ),
    ]
