# Generated by Django 5.1.3 on 2024-12-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_remove_empresa_menu_regalo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='plato_menu1',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/platos-menu'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='plato_menu2',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/platos-menu'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='plato_menu3',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/platos-menu'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='plato_menu4',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/Platos-menu'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='plato_menu5',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/Platos-menu'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='plato_menu6',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/platos-menu'),
        ),
    ]
