# Generated by Django 5.1.3 on 2024-12-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_empresa_plato_menu1_empresa_plato_menu2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nombreUrl',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
