# Generated by Django 5.1.3 on 2025-01-07 20:41

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_alter_perfil_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peluqueria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Empresa')),
                ('subtitulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subtitulo')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='descripcion')),
                ('imagen_header', models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/header/peluquerias')),
            ],
            options={
                'verbose_name': 'Peluqueria',
                'verbose_name_plural': 'Peluquerias',
                'ordering': ['nombre', 'subtitulo'],
            },
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre', 'subtitulo'], 'verbose_name': 'Catalogo', 'verbose_name_plural': 'Catalogos'},
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='chefs_activo',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='clientes_activo',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='comentarios_activo',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='contactar_activo',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='email',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='eventos_activo',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='galeria_activo',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='imagen_galeria1',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='imagen_galeria2',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='imagen_galeria3',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='imagen_galeria4',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='imagen_galeria5',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='imagen_galeria6',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='imagen_galeria7',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='imagen_galeria8',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='imagen_nosotros',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='imagen_nosotros_fondo',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='imagen_portada',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='menu_oferta1',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='menu_oferta2',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='menu_oferta3',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='menu_regalo_activo',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='nombreUrl',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='parrafo1',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='parrafo2',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='parrafo3',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='parrafo4',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='parrafo5',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='plato_menu1',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='plato_menu2',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='plato_menu3',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='plato_menu4',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='plato_menu5',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='plato_menu6',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='platos_menu_activo',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='quienes_somos_activo',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='reservar_activo',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='tipo_empresa',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='video_header',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='video_nosotros',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='imagen_header',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/header/catalogos'),
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Empresa')),
                ('subtitulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subtitulo')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='descripcion')),
                ('imagen_header', models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/header')),
                ('video_header', models.CharField(blank=True, max_length=500, null=True, verbose_name='video_header')),
                ('quienes_somos_activo', models.BooleanField(blank=True, null=True, verbose_name='Agregar sección Sobre Nosotros')),
                ('parrafo1', models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo1')),
                ('parrafo2', models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo2')),
                ('parrafo3', models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo3')),
                ('parrafo4', models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo4')),
                ('parrafo5', models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo5')),
                ('imagen_nosotros', models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/nosotros')),
                ('imagen_nosotros_fondo', models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/nosotros')),
                ('video_nosotros', models.CharField(blank=True, max_length=500, null=True, verbose_name='video_nosotros')),
                ('menu_regalo_activo', models.BooleanField(blank=True, null=True, verbose_name='Agregar sección para vender menu de regalo')),
                ('menu_oferta1', tinymce.models.HTMLField(blank=True, null=True)),
                ('menu_oferta2', tinymce.models.HTMLField(blank=True, null=True)),
                ('menu_oferta3', tinymce.models.HTMLField(blank=True, null=True)),
                ('clientes_activo', models.BooleanField(blank=True, null=True, verbose_name='Agregar sección para ver clientes')),
                ('platos_menu_activo', models.BooleanField(blank=True, null=True, verbose_name='Agregar sección de platos')),
                ('plato_menu1', models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/platos-menu')),
                ('plato_menu2', models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/platos-menu')),
                ('plato_menu3', models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/platos-menu')),
                ('plato_menu4', models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/Platos-menu')),
                ('plato_menu5', models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/Platos-menu')),
                ('plato_menu6', models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/platos-menu')),
                ('comentarios_activo', models.BooleanField(blank=True, null=True, verbose_name='Agregar sección de comentarios')),
                ('eventos_activo', models.BooleanField(blank=True, null=True, verbose_name='Agregar sección de enventos')),
                ('chefs_activo', models.BooleanField(blank=True, null=True, verbose_name='Agregar sección de chefs')),
                ('reservar_activo', models.BooleanField(blank=True, null=True, verbose_name='Agregar sección para reservas')),
                ('galeria_activo', models.BooleanField(blank=True, null=True, verbose_name='Agregar sección Galería')),
                ('imagen_galeria1', models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/galeria')),
                ('imagen_galeria2', models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/galeria')),
                ('imagen_galeria3', models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/galeria')),
                ('imagen_galeria4', models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/galeria')),
                ('imagen_galeria5', models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/galeria')),
                ('imagen_galeria6', models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/galeria')),
                ('imagen_galeria7', models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/galeria')),
                ('imagen_galeria8', models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/galeria')),
                ('contactar_activo', models.BooleanField(blank=True, null=True, verbose_name='Agregar sección para contactar')),
                ('horario', models.CharField(blank=True, max_length=500, null=True, verbose_name='horario')),
                ('pais', models.CharField(max_length=100, verbose_name='Pais de la Empresa')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Nombre de la Ciudad')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/principal')),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/portada')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Direccion')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de telefono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electronico')),
                ('latitud', models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitud')),
                ('longitud', models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitud')),
                ('nombreUrl', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('tipo_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='home.tipoempresa', verbose_name='Tipo de Empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['pais', 'ciudad'],
            },
        ),
    ]
