# Generated by Django 5.1.3 on 2025-01-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_peluqueria_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='latitud',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='longitud',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='peluqueria',
            name='latitud',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='peluqueria',
            name='longitud',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitud'),
        ),
    ]
