# Generated by Django 5.1.3 on 2025-01-08 15:56

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_empresa_latitud_empresa_longitud_peluqueria_latitud_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Peluqueria',
        ),
        migrations.AddField(
            model_name='empresa',
            name='chefs_activo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agregar sección de chefs'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ciudad',
            field=models.CharField(default=1, max_length=100, verbose_name='Nombre de la Ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='clientes_activo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agregar sección para ver clientes'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='comentarios_activo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agregar sección de comentarios'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='contactar_activo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agregar sección para contactar'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electronico'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='eventos_activo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agregar sección de enventos'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='galeria_activo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agregar sección Galería'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='horario',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='horario'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/principal'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_galeria1',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/galeria'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_galeria2',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/galeria'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_galeria3',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/galeria'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_galeria4',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/galeria'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_galeria5',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/galeria'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_galeria6',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/galeria'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_galeria7',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/galeria'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_galeria8',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/galeria'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_nosotros',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/nosotros'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_nosotros_fondo',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/nosotros'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/portada'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='menu_oferta1',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='menu_oferta2',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='menu_oferta3',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='menu_regalo_activo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agregar sección para vender menu de regalo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombreUrl',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pais',
            field=models.CharField(default=2, max_length=100, verbose_name='Pais de la Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='parrafo1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo1'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='parrafo2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo2'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='parrafo3',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo3'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='parrafo4',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo4'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='parrafo5',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo5'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='plato_menu1',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/platos-menu'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='plato_menu2',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/platos-menu'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='plato_menu3',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/platos-menu'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='plato_menu4',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/Platos-menu'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='plato_menu5',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/Platos-menu'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='plato_menu6',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/platos-menu'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='platos_menu_activo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agregar sección de platos'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='quienes_somos_activo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agregar sección Sobre Nosotros'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='reservar_activo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agregar sección para reservas'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de telefono'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='home.tipoempresa', verbose_name='Tipo de Empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='video_header',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='video_header'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='video_nosotros',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='video_nosotros'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='imagen_header',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/header'),
        ),
        migrations.DeleteModel(
            name='Restaurante',
        ),
    ]
