# Generated by Django 5.1.3 on 2025-01-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_alter_empresa_options_alter_empresa_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre_de_la_empresa', 'titulo_header'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='imagen_galeria1',
            new_name='image3_galeria',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='imagen_galeria2',
            new_name='image4_galeria',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='imagen_galeria3',
            new_name='image5_galeria',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='imagen_galeria4',
            new_name='image6_galeria',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='imagen_galeria5',
            new_name='image7_galeria',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='imagen_galeria6',
            new_name='image8_galeria',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='imagen_nosotros',
            new_name='imagen1_nosotros',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='imagen_galeria7',
            new_name='imagen2_galeria',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='imagen_nosotros_fondo',
            new_name='imagen2_nosotros_fondo',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='imagen_galeria8',
            new_name='imagen9_galeria',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='nombre',
            new_name='nombre_de_la_empresa',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='parrafo1',
            new_name='titulo_trabajadores',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='parrafo2',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='parrafo3',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='parrafo4',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='parrafo5',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='subtitulo',
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_fondo_header',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/header'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_logo_empresa',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/logos/header'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_servicio1',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/servicios'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_servicio2',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/servicios'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_servicio3',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/servicios'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_tarifa1',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/servicios'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_tarifa2',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/servicios'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_trabajador1',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/trabajadores'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_trabajador2',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/trabajadores'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_trabajador3',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/trabajadores'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre1_comentario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la persona que hace el comentario 1'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre2_comentario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la persona que hace el comentario 2'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre3_comentario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la persona que hace el comentario 3'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_servicio1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo servicio 1'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_servicio10_tarifa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Titulo tarifa 10'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_servicio1_tarifa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Titulo tarifa 1'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_servicio2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo servicio 2'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_servicio2_tarifa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Titulo tarifa 2'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_servicio3',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo servicio 3'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_servicio3_tarifa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Titulo tarifa 3'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_servicio4_tarifa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Titulo tarifa 4'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_servicio5_tarifa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Titulo tarifa 5'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_servicio6_tarifa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Titulo tarifa 6'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_servicio7_tarifa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Titulo tarifa 7'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_servicio8_tarifa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Titulo tarifa 8'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_servicio9_tarifa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Titulo tarifa 9'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_trabajador1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='trabajador 1'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_trabajador2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='trabajador 2'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_trabajador3',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='trabajador 3'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='parrafo1_comentario',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo cmentario 1'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='parrafo1_sobrenosotros',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo sobrenosotros 1'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='parrafo2_comentario',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo comentario 2'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='parrafo2_sobrenosotros',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo sobrenosotros 2'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='parrafo3_comentario',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo comentario 3'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='parrafo3_sobrenosotros',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo sobrenosotros 3'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='parrafo4_sobrenosotros',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo sobrenosotros 4'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='parrafo5_sobrenosotros',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo sobrenosotros 5'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='parrafo_servicios1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo servicio 4'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='parrafo_servicios2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo servicio 5'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='parrafo_servicios3',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo servicio 6'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='precio_servicio10_tarifa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='precio tarifa 10'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='precio_servicio1_tarifa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='precio tarifa 1'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='precio_servicio2_tarifa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='precio tarifa 2'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='precio_servicio3_tarifa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='precio tarifa 3'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='precio_servicio4_tarifa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='precio tarifa 4'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='precio_servicio5_tarifa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='precio tarifa 5'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='precio_servicio6_tarifa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='precio tarifa 6'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='precio_servicio7_tarifa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='precio tarifa 7'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='precio_servicio8_tarifa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='precio tarifa 8'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='precio_servicio9_tarifa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='precio tarifa 9'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='subtitulo1_header',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='subtitulo 1 header'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='subtitulo2_header',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='subtitulo 2 header'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='titulo1_galeria',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Titulo galeria'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='titulo_header',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='titulo header'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='titulo_servicios',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='titulo servicios'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='titulo_sobrenosotros',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo sobrenosotros 1'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='titulo_tarifa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Titulo tarifa'),
        ),
    ]
