# Generated by Django 5.1.3 on 2025-01-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='imagen1_comentario',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/servicios'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen2_comentario',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/servicios'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen3_comentario',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/servicios'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen3_nosotros',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/nosotros'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='parrafo1_comentario',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo comentario 1'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='titulo_tarifa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Titulo sccion de tarifa'),
        ),
    ]
