# Generated by Django 5.1.3 on 2025-01-11 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_empresa_propietario_sitio_web'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='Propietario_sitio_web',
        ),
        migrations.AddField(
            model_name='empresa',
            name='propietario_sitio_web',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
            preserve_default=False,
        ),
    ]
