# Generated by Django 5.1.3 on 2025-01-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_remove_empresa_plato_menu1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='imagen_chef1',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/chefs/', verbose_name='Agregar imagen Chef 1'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_chef2',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/chefs/', verbose_name='Agregar imagen Chef 2'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_chef3',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/chefs/', verbose_name='Agregar imagen Chef 3'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_portada_reserva',
            field=models.ImageField(blank=True, null=True, upload_to='reservas/', verbose_name='Imagen Portada Reserva'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_servicio4',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/servicios'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_chef1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Introduzca el nombre del Chef 1'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_chef2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Introduzca el nombre del Chef 2'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_chef3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Introduzca el nombre del Chef 3'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_servicio4',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='desacribir parrafo servicio 4'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='parrafo_servicios4',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='describir el parrafo servicio 4'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='imagen1_comentario',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/comentarios'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='imagen2_comentario',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/comentarios'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='imagen3_comentario',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/imagenes/comentarios'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre_servicio1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='desacribir parrafo servicio 1'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre_servicio2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='desacribir parrafo servicio 2'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre_servicio3',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='desacribir parrafo servicio 3'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='parrafo1_sobrenosotros',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo para describir sobrenosotros 1'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='parrafo2_sobrenosotros',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo para describir sobrenosotros 2'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='parrafo3_sobrenosotros',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo para describir sobrenosotros 3'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='parrafo4_sobrenosotros',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo para describir sobrenosotros 4'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='parrafo5_sobrenosotros',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo para describir sobrenosotros 5'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='parrafo_servicios1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='describir el parrafo servicio 1'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='parrafo_servicios2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='describir el parrafo servicio 2'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='parrafo_servicios3',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='describir el parrafo servicio 3'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='titulo_sobrenosotros',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parrafo para describir sobrenosotros 1'),
        ),
    ]
