# Generated by Django 5.1.3 on 2026-08-09 10:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_receta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nombreUrl',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='Elija el nombre de la URl sin espacios'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_empresa',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='home.tipoempresa', verbose_name='Elija el tipo de Empresa'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='categoria',
            field=models.CharField(choices=[('entradas', 'Entradas'), ('platos_principales', 'Platos Principales'), ('postres', 'Postres'), ('bebidas', 'Bebidas'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
        migrations.AlterField(
            model_name='receta',
            name='cuerpo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='receta',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recetas/'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='resumen',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='receta',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='home.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-fecha'],
                'unique_together': {('usuario', 'empresa')},
            },
        ),
    ]
