# Generated by Django 5.1.3 on 2026-08-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0079_valoracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(choices=[('inicio', 'Inicio'), ('blog', 'Blog'), ('mapa', 'Mapa'), ('galeria', 'Galería'), ('recetas', 'Recetas'), ('servicios', 'Servicios (Preguntas y Moneda)'), ('donativos', 'Donativos'), ('empresas', 'Empresas (Explorar negocios)'), ('extranjeros', 'Extranjeros (Consulados, Embajadas, Abogados)'), ('contacto', 'Contacto')], max_length=50, unique=True, verbose_name='Enlace del menú')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre visible en el menú')),
                ('activo', models.BooleanField(default=True, verbose_name='Mostrar en el menú')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Sección del menú',
                'verbose_name_plural': 'Secciones del menú',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
