# Generated by Django 5.1.7 on 2026-08-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0081_seed_secciones_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='header_activo',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Agregar sección de Cabecera'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='servicios_activo',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Agregar sección de servicios'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tarifa_activo',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Agregar sección de tarifas/catálogo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='trabajadores_activo',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Agregar sección de trabajadores'),
        ),
    ]
