# Generated by Django 5.1.7 on 2026-08-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0082_empresa_header_activo_empresa_servicios_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='chefs_activo',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Agregar sección de chefs'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='clientes_activo',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Agregar sección para ver clientes'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='comentarios_activo',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Agregar sección de comentarios'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='contactar_activo',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Agregar sección para contactar'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='eventos_activo',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Agregar sección de enventos'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='galeria_activo',
            field=models.BooleanField(blank=True, default=True, verbose_name='Agregar sección Galería'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='menu_regalo_activo',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Agregar sección para vender menu de regalo'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='platos_menu_activo',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Agregar sección de platos'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='quienes_somos_activo',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Agregar sección Sobre Nosotros'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='reservar_activo',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Agregar sección para reservas'),
        ),
    ]
