# Generated by Django 5.1.3 on 2026-09-27 18:06

from django.db import migrations, models


def crear_configuracion_historias(apps, schema_editor):
    configuracion = apps.get_model('home', 'HistoriaConfiguracion')
    configuracion.objects.get_or_create(pk=1, defaults={'video_youtube_id': '3dJC1Z9Sl78'})

    seccion_menu = apps.get_model('home', 'SeccionMenu')
    seccion_menu.objects.get_or_create(
        clave='historias',
        defaults={'nombre': 'Historias', 'activo': True, 'orden': 2},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_alter_empresa_chefs_activo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_youtube_id', models.CharField(default='3dJC1Z9Sl78', help_text='Pega una URL de YouTube o su ID. Se guardará únicamente el ID validado.', max_length=11, verbose_name='ID o URL del vídeo de YouTube')),
            ],
            options={
                'verbose_name': 'Configuración de Historias',
                'verbose_name_plural': 'Configuración de Historias',
            },
        ),
        migrations.CreateModel(
            name='HistoriaPropuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('ciudad_pais', models.CharField(max_length=150, verbose_name='Ciudad y país')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=40, verbose_name='Teléfono o WhatsApp')),
                ('historia', models.TextField(max_length=2500, verbose_name='Historia')),
                ('preferencia_contacto', models.CharField(choices=[('email', 'Correo electrónico'), ('telefono', 'Teléfono o WhatsApp'), ('indiferente', 'Me es indiferente')], default='email', max_length=20, verbose_name='Preferencia de contacto')),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('contactada', 'Contactada'), ('conversacion', 'En conversación'), ('cerrada', 'Cerrada')], default='nueva', max_length=20, verbose_name='Estado')),
                ('recibida_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de recepción')),
                ('actualizada_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Propuesta de historia',
                'verbose_name_plural': 'Propuestas de historias',
                'ordering': ['-recibida_en'],
            },
        ),
        migrations.AlterField(
            model_name='seccionmenu',
            name='clave',
            field=models.CharField(choices=[('inicio', 'Inicio'), ('historias', 'Historias'), ('blog', 'Blog'), ('mapa', 'Mapa'), ('galeria', 'Galería'), ('recetas', 'Recetas'), ('servicios', 'Servicios (Preguntas y Moneda)'), ('donativos', 'Donativos'), ('empresas', 'Empresas (Explorar negocios)'), ('extranjeros', 'Extranjeros (Consulados, Embajadas, Abogados)'), ('contacto', 'Contacto')], max_length=50, unique=True, verbose_name='Enlace del menú'),
        ),
        migrations.RunPython(crear_configuracion_historias, migrations.RunPython.noop),
    ]
