# Generated by Django 5.1.3 on 2026-09-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0084_historiaconfiguracion_historiapropuesta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaconfiguracion',
            name='video_youtube_id',
            field=models.CharField(default='3dJC1Z9Sl78', help_text='Pega una URL de YouTube o su ID. Se guardará únicamente el ID validado.', max_length=200, verbose_name='ID o URL del vídeo de YouTube'),
        ),
    ]
