# Generated by Django 5.1.3 on 2026-09-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0085_alter_historiaconfiguracion_video_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiapropuesta',
            name='lugar_grabacion',
            field=models.CharField(blank=True, choices=[('ubicacion_propia', 'En mi restaurante, bar, empresa u hogar'), ('estudio_mundonica', 'En el estudio de Mundónica, en Oiartzun (Gipuzkoa, España)')], default='', max_length=20, verbose_name='¿Dónde prefieres que grabemos el podcast o la entrevista?'),
        ),
        migrations.AddField(
            model_name='historiapropuesta',
            name='preferencia_grabacion',
            field=models.CharField(blank=True, choices=[('laborable_manana', 'Lunes a viernes por la mañana'), ('laborable_tarde', 'Lunes a viernes por la tarde'), ('sabado_manana', 'Sábado por la mañana'), ('sabado_tarde', 'Sábado por la tarde'), ('domingo_manana', 'Domingo por la mañana'), ('domingo_tarde', 'Domingo por la tarde'), ('flexible', 'Tengo flexibilidad de fecha y hora')], default='', max_length=20, verbose_name='Preferencia para grabar el podcast o la entrevista'),
        ),
    ]
