# Generated by Django 5.1.3 on 2026-10-09 11:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0086_historia_preferencias_grabacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="codigo_postal",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Código postal"
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="descripcion_directorio",
            field=models.TextField(
                blank=True, verbose_name="Descripción del directorio"
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="estado_publicacion",
            field=models.CharField(
                choices=[
                    ("draft", "Borrador"),
                    ("published", "Publicado"),
                    ("archived", "Archivado"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
                verbose_name="Estado de publicación",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="estado_reclamacion",
            field=models.CharField(
                choices=[
                    ("unclaimed", "No reclamado"),
                    ("claimed", "Reclamado"),
                    ("under_review", "En revisión"),
                ],
                db_index=True,
                default="unclaimed",
                max_length=20,
                verbose_name="Estado de reclamación",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="estado_verificacion",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("verified", "Verificado"),
                    ("rejected", "Rechazado"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Estado de verificación",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="fecha_actualizacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="empresa",
            name="fecha_incorporacion",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="identificador_externo",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Identificador externo",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="provincia",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Provincia"
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="region",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Comunidad autónoma o región"
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="relacion_nicaragua",
            field=models.TextField(blank=True, verbose_name="Relación con Nicaragua"),
        ),
        migrations.AddField(
            model_name="empresa",
            name="sitio_web",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Página web"
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="tipo_perfil",
            field=models.CharField(
                choices=[
                    ("business", "Empresa o negocio"),
                    ("organization", "Asociación u organización"),
                    ("person", "Profesional o persona"),
                    ("project", "Proyecto o iniciativa"),
                ],
                db_index=True,
                default="business",
                max_length=20,
                verbose_name="Tipo de perfil",
            ),
        ),
        migrations.AddField(
            model_name="tipoempresa",
            name="plantilla_perfil",
            field=models.CharField(
                choices=[
                    ("generica", "Genérica"),
                    ("restaurante", "Restaurante"),
                    ("peluqueria", "Peluquería"),
                    ("comercio", "Comercio"),
                ],
                default="generica",
                max_length=20,
                verbose_name="Plantilla de perfil",
            ),
        ),
        migrations.CreateModel(
            name="ImportacionPerfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identificador_externo", models.CharField(max_length=50, unique=True)),
                (
                    "fuente_informacion",
                    models.CharField(default="mundonica_perfiles.csv", max_length=100),
                ),
                ("url_origen", models.URLField(blank=True, max_length=500)),
                ("hoja_origen", models.CharField(blank=True, max_length=100)),
                ("notas_internas", models.TextField(blank=True)),
                ("canal_contacto", models.CharField(blank=True, max_length=50)),
                (
                    "disponibilidad_contacto",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "tipo_direccion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("business_or_public", "Negocio o dirección pública"),
                            ("institutional_contact", "Contacto institucional"),
                            ("registry_not_for_visit", "Registral, no visitable"),
                            ("not_provided", "No informada"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "precision_localizacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("address_unverified", "Dirección sin verificar"),
                            ("municipality_only", "Solo municipio"),
                            ("unknown", "Desconocida"),
                        ],
                        max_length=30,
                    ),
                ),
                ("verificacion_original", models.CharField(blank=True, max_length=255)),
                (
                    "hash_fila",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("primera_importacion", models.DateTimeField(auto_now_add=True)),
                ("ultima_importacion", models.DateTimeField(auto_now=True)),
                (
                    "resultado_validacion",
                    models.CharField(
                        choices=[
                            ("valid", "Válido"),
                            ("warnings", "Con advertencias"),
                            ("error", "Error"),
                        ],
                        default="valid",
                        max_length=20,
                    ),
                ),
                (
                    "datos_ultima_importacion",
                    models.JSONField(blank=True, default=dict),
                ),
                ("campos_en_conflicto", models.JSONField(blank=True, default=dict)),
                (
                    "empresa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="importacion_perfil",
                        to="home.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Importación de perfil",
                "verbose_name_plural": "Importaciones de perfiles",
                "ordering": ["identificador_externo"],
            },
        ),
    ]
