# Generated by Django 5.1.3 on 2026-10-09 11:46

from django.db import migrations


def publicar_historicos(apps, schema_editor):
    Empresa = apps.get_model("home", "Empresa")
    TipoEmpresa = apps.get_model("home", "TipoEmpresa")
    Empresa.objects.filter(identificador_externo__isnull=True).update(
        estado_publicacion="published", tipo_perfil="business"
    )
    plantillas = {
        "Restaurante": "restaurante",
        "Peluquería": "peluqueria",
        "Comercio": "comercio",
        "Empresa": "generica",
    }
    for nombre, plantilla in plantillas.items():
        TipoEmpresa.objects.filter(nombre=nombre).update(plantilla_perfil=plantilla)


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0087_directorio_perfiles_fase1"),
    ]

    operations = [migrations.RunPython(publicar_historicos, migrations.RunPython.noop)]
