# Generated by Django 5.1.3 on 2026-10-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0088_publicar_perfiles_historicos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
