# Generated by Django 5.1.3 on 2026-10-09 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0089_actualizar_fecha_perfil"),
    ]

    operations = [
        migrations.AddField(
            model_name="importacionperfil",
            name="errores_validacion",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="tipo_empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="empresas",
                to="home.tipoempresa",
                verbose_name="Elija el tipo de Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="importacionperfil",
            name="empresa",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="importacion_perfil",
                to="home.empresa",
            ),
        ),
    ]
